Vagrant.configure("2") do |config|

    config.vm.provider :virtualbox do |v|
        v.name = "basedev"
        v.customize [
            "modifyvm", :id,
            "--name", "basedev",
            "--memory", 1024,
            "--natdnshostresolver1", "on",
            "--cpus", 1,
        ]
    end

    config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"
    config.vm.box = "ubuntu/trusty64"

    config.vm.network :private_network, ip: "10.10.10.10"
    config.vm.network :forwarded_port, guest: 22, host: 2220, id: 'ssh'
    config.ssh.forward_agent = true

    config.vm.provision "file", source: "../common/keys/dev.pub", destination: "/home/vagrant/.ssh/dev.pub"
    config.vm.provision "shell", inline: "/bin/cat /home/vagrant/.ssh/dev.pub >> /home/vagrant/.ssh/authorized_keys"
end
